config/routes.rb
Rails.application.routes.draw do

  resources :item_types
  devise_for :users
  root to: "orders#new"
  
  get '/orders/:id/submit', to: 'orders#submit'
  get '/orders/:id/resume', to: 'orders#resume'
  post '/orders/:id/complete', to: 'orders#complete'
  #get '/orders/:id/print_ticket', to: 'orders#print_ticket'
  get '/orders/print_info_pape', to: 'orders#print_info_pape'
  get '/orders/:id/print_order', to: 'orders#print_order'

  resources :order_item_histories
  resources :order_histories
  
  resources :orders do
    resources :order_items
  end
  
  resources :order_statuses
  resources :item_prices
  resources :stock_histories
  resources :stocks

  resources :items do
    get 'search', on: :collection
  end

  resources :brands

  get '/test_ticket', to: 'ticket_test#ticket'
  #get '/report_order_item', to: 'report_order_item#index'
  get '/reports/items', to: 'reports#items'
  get '/reports/totals_day', to: 'reports#totals_day'


  #get 'search_brands', to: 'brands#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  belongs_to :item_type
  has_one :item_price, :dependent => :destroy
  has_one :stock, :dependent => :destroy

  validates_presence_of :name
  validates :name, uniqueness: true
  validates :code, uniqueness: true, allow_blank: true

  before_validation :default_values
  #before_destroy :drop_related

  protected
  def default_values
    
    if code.blank?
    	self.code = nil
    end
    
    if brand_id.nil?
      self.brand_id = Brand.find_by(name: "GENERICO").id
    end

    if item_type_id.nil?
      self.item_type_id = ItemType.find_by(name: "ITEM").id
    end

  end

#  def drop_related
#      Stock.where("item_id=?", id).delete_all
#      ItemPrice.where("item_id=?", id).delete_all
#    end

end

app/models/item_price.rb
class ItemPrice < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if variable_price.blank?
    	self.variable_price = false
    end
    
  end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
	has_many :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_destroy :create_history

  private
  	def create_history
  	  order_history = OrderHistory.create!(order_id: id, name: name, order_status: order_status, count_items: count_items, subtotal_amount: subtotal_amount, total_discount: total_discount, total_amount: total_amount, paid: paid, change: change, discount_percentage: discount_percentage)

  	  order_items = OrderItem.where("order_id=?", id).includes(item: :item_price)

  	  order_items.each do |order_item|
        tmp_order_item_price = order_item.item.item_price
        tmp_price_per_unit = tmp_order_item_price.price

        if tmp_order_item_price.variable_price
          tmp_custom_price = order_item.custom_price
          tmp_price_per_unit = tmp_custom_price.to_f if tmp_custom_price.present?
        end

        OrderItemHistory.create! order_history_id: order_history.id, order_id: order_item.order_id, item_id: order_item.item_id, quantity: order_item.quantity, discount_amount_per_unit: order_item.discount_amount_per_unit, item_name: order_item.item.name, item_price: tmp_price_per_unit

        stockItem = order_item.item.stock
        if stockItem.blank?
          stockItem = Stock.create! item_id: order_item.item_id
        end

        if !stockItem.shared_stock
          stockItem.units = 0 if stockItem.units.blank?
          stockItem.units -= order_item.quantity
          stockItem.save
        else
          if stockItem.shared_stock_item_id.present?
            stockItemShared = Stock.find_by(item_id: stockItem.shared_stock_item_id)
            stockItemShared.units = 0 if stockItemShared.units.blank?
            stockItemShared.units -= (order_item.quantity*stockItem.shared_stock_consume_units)
            stockItemShared.save
          else
            puts "There is an error in configuration of shared item, please check"
            stockItem.units = 0 if stockItem.units.blank?
            stockItem.units -= order_item.quantity
            stockItem.save
          end
        end

      end
      OrderItem.where("order_id=?", id).delete_all

  	end
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :order_status
  has_many :order_item_histories

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order_item_history.rb
class OrderItemHistory < ApplicationRecord
  belongs_to :order_history
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if item_shareable.blank?
    	self.item_shareable = false
    end
    
    if shared_stock.blank?
    	self.shared_stock = false
    end

  end
end

app/models/stock_history.rb
class StockHistory < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/order_statuses_controller.rb
class OrderStatusesController < ApplicationController
  before_action :set_order_status, only: [:show, :edit, :update, :destroy]

  # GET /order_statuses
  # GET /order_statuses.json
  def index
    @order_statuses = OrderStatus.all
  end

  # GET /order_statuses/1
  # GET /order_statuses/1.json
  def show
  end

  # GET /order_statuses/new
  def new
    @order_status = OrderStatus.new
  end

  # GET /order_statuses/1/edit
  def edit
  end

  # POST /order_statuses
  # POST /order_statuses.json
  def create
    @order_status = OrderStatus.new(order_status_params)

    respond_to do |format|
      if @order_status.save
        format.html { redirect_to @order_status, notice: 'Order status was successfully created.' }
        format.json { render :show, status: :created, location: @order_status }
      else
        format.html { render :new }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_statuses/1
  # PATCH/PUT /order_statuses/1.json
  def update
    respond_to do |format|
      if @order_status.update(order_status_params)
        format.html { redirect_to @order_status, notice: 'Order status was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_status }
      else
        format.html { render :edit }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_statuses/1
  # DELETE /order_statuses/1.json
  def destroy
    @order_status.destroy
    respond_to do |format|
      format.html { redirect_to order_statuses_url, notice: 'Order status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_status
      @order_status = OrderStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_status_params
      params.require(:order_status).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_statuses_helper.rb
module OrderStatusesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/order_statuses/_form.html.erb
<%= form_with(model: order_status, local: true) do |form| %>
  <% if order_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_status.errors.count, "error") %> prohibited this order_status from being saved:</h2>

      <ul>
        <% order_status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_statuses/edit.html.erb
<h1>Editing Order Status</h1>

<%= render 'form', order_status: @order_status %>

<%= link_to 'Show', @order_status %> |
<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_statuses.each do |order_status| %>
      <tr>
        <td><%= order_status.name %></td>
        <td><%= order_status.description %></td>
        <td><%= link_to 'Show', order_status %></td>
        <td><%= link_to 'Edit', edit_order_status_path(order_status) %></td>
        <td><%= link_to 'Destroy', order_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Status', new_order_status_path %>

app/views/order_statuses/new.html.erb
<h1>New Order Status</h1>

<%= render 'form', order_status: @order_status %>

<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order_status.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order_status.description %>
</p>

<%= link_to 'Edit', edit_order_status_path(@order_status) %> |
<%= link_to 'Back', order_statuses_path %>