config/routes.rb
Rails.application.routes.draw do

  resources :item_types
  devise_for :users
  root to: "orders#new"
  
  get '/orders/:id/submit', to: 'orders#submit'
  get '/orders/:id/resume', to: 'orders#resume'
  post '/orders/:id/complete', to: 'orders#complete'
  #get '/orders/:id/print_ticket', to: 'orders#print_ticket'
  get '/orders/print_info_pape', to: 'orders#print_info_pape'
  get '/orders/:id/print_order', to: 'orders#print_order'

  resources :order_item_histories
  resources :order_histories
  
  resources :orders do
    resources :order_items
  end
  
  resources :order_statuses
  resources :item_prices
  resources :stock_histories
  resources :stocks

  resources :items do
    get 'search', on: :collection
  end

  resources :brands

  get '/test_ticket', to: 'ticket_test#ticket'
  #get '/report_order_item', to: 'report_order_item#index'
  get '/reports/items', to: 'reports#items'
  get '/reports/totals_day', to: 'reports#totals_day'


  #get 'search_brands', to: 'brands#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  belongs_to :item_type
  has_one :item_price, :dependent => :destroy
  has_one :stock, :dependent => :destroy

  validates_presence_of :name
  validates :name, uniqueness: true
  validates :code, uniqueness: true, allow_blank: true

  before_validation :default_values
  #before_destroy :drop_related

  protected
  def default_values
    
    if code.blank?
    	self.code = nil
    end
    
    if brand_id.nil?
      self.brand_id = Brand.find_by(name: "GENERICO").id
    end

    if item_type_id.nil?
      self.item_type_id = ItemType.find_by(name: "ITEM").id
    end

  end

#  def drop_related
#      Stock.where("item_id=?", id).delete_all
#      ItemPrice.where("item_id=?", id).delete_all
#    end

end

app/models/item_price.rb
class ItemPrice < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if variable_price.blank?
    	self.variable_price = false
    end
    
  end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
	has_many :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_destroy :create_history

  private
  	def create_history
  	  order_history = OrderHistory.create!(order_id: id, name: name, order_status: order_status, count_items: count_items, subtotal_amount: subtotal_amount, total_discount: total_discount, total_amount: total_amount, paid: paid, change: change, discount_percentage: discount_percentage)

  	  order_items = OrderItem.where("order_id=?", id).includes(item: :item_price)

  	  order_items.each do |order_item|
        tmp_order_item_price = order_item.item.item_price
        tmp_price_per_unit = tmp_order_item_price.price

        if tmp_order_item_price.variable_price
          tmp_custom_price = order_item.custom_price
          tmp_price_per_unit = tmp_custom_price.to_f if tmp_custom_price.present?
        end

        OrderItemHistory.create! order_history_id: order_history.id, order_id: order_item.order_id, item_id: order_item.item_id, quantity: order_item.quantity, discount_amount_per_unit: order_item.discount_amount_per_unit, item_name: order_item.item.name, item_price: tmp_price_per_unit

        stockItem = order_item.item.stock
        if stockItem.blank?
          stockItem = Stock.create! item_id: order_item.item_id
        end

        if !stockItem.shared_stock
          stockItem.units = 0 if stockItem.units.blank?
          stockItem.units -= order_item.quantity
          stockItem.save
        else
          if stockItem.shared_stock_item_id.present?
            stockItemShared = Stock.find_by(item_id: stockItem.shared_stock_item_id)
            stockItemShared.units = 0 if stockItemShared.units.blank?
            stockItemShared.units -= (order_item.quantity*stockItem.shared_stock_consume_units)
            stockItemShared.save
          else
            puts "There is an error in configuration of shared item, please check"
            stockItem.units = 0 if stockItem.units.blank?
            stockItem.units -= order_item.quantity
            stockItem.save
          end
        end

      end
      OrderItem.where("order_id=?", id).delete_all

  	end
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :order_status
  has_many :order_item_histories

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order_item_history.rb
class OrderItemHistory < ApplicationRecord
  belongs_to :order_history
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if item_shareable.blank?
    	self.item_shareable = false
    end
    
    if shared_stock.blank?
    	self.shared_stock = false
    end

  end
end

app/models/stock_history.rb
class StockHistory < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/item_prices_controller.rb
class ItemPricesController < ApplicationController
  before_action :set_item_price, only: [:show, :edit, :update, :destroy]

  # GET /item_prices
  # GET /item_prices.json
  def index
    @item_prices = ItemPrice.all
  end

  # GET /item_prices/1
  # GET /item_prices/1.json
  def show
  end

  # GET /item_prices/new
  def new
    @item_price = ItemPrice.new
  end

  # GET /item_prices/1/edit
  def edit
  end

  # POST /item_prices
  # POST /item_prices.json
  def create
    @item_price = ItemPrice.new(item_price_params)

    respond_to do |format|
      if @item_price.save
        format.html { redirect_to @item_price, notice: 'Item price was successfully created.' }
        format.json { render :show, status: :created, location: @item_price }
      else
        format.html { render :new }
        format.json { render json: @item_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_prices/1
  # PATCH/PUT /item_prices/1.json
  def update
    respond_to do |format|
      if @item_price.update(item_price_params)
        format.html { redirect_to @item_price, notice: 'Item price was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_price }
      else
        format.html { render :edit }
        format.json { render json: @item_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_prices/1
  # DELETE /item_prices/1.json
  def destroy
    @item_price.destroy
    respond_to do |format|
      format.html { redirect_to item_prices_url, notice: 'Item price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_price
      @item_price = ItemPrice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_price_params
      params.require(:item_price).permit(:item_id, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/item_prices_helper.rb
module ItemPricesHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/item_prices/_form.html.erb
<%= form_with(model: item_price, local: true) do |form| %>
  <% if item_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_price.errors.count, "error") %> prohibited this item_price from being saved:</h2>

      <ul>
        <% item_price.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :variable_price %>
    <%= form.check_box :variable_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_prices/edit.html.erb
<h1>Editing Item Price</h1>

<%= render 'form', item_price: @item_price %>

<%= link_to 'Show', @item_price %> |
<%= link_to 'Back', item_prices_path %>

app/views/item_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Prices</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_prices.each do |item_price| %>
      <tr>
        <td><%= item_price.item_id %></td>
        <td><%= item_price.price %></td>
        <td><%= link_to 'Show', item_price %></td>
        <td><%= link_to 'Edit', edit_item_price_path(item_price) %></td>
        <td><%= link_to 'Destroy', item_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Price', new_item_price_path %>

app/views/item_prices/new.html.erb
<h1>New Item Price</h1>

<%= render 'form', item_price: @item_price %>

<%= link_to 'Back', item_prices_path %>

app/views/item_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_price.item_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item_price.price %>
</p>

<%= link_to 'Edit', edit_item_price_path(@item_price) %> |
<%= link_to 'Back', item_prices_path %>