config/routes.rb
Rails.application.routes.draw do

  resources :item_types
  devise_for :users
  root to: "orders#new"
  
  get '/orders/:id/submit', to: 'orders#submit'
  get '/orders/:id/resume', to: 'orders#resume'
  post '/orders/:id/complete', to: 'orders#complete'
  #get '/orders/:id/print_ticket', to: 'orders#print_ticket'
  get '/orders/print_info_pape', to: 'orders#print_info_pape'
  get '/orders/:id/print_order', to: 'orders#print_order'

  resources :order_item_histories
  resources :order_histories
  
  resources :orders do
    resources :order_items
  end
  
  resources :order_statuses
  resources :item_prices
  resources :stock_histories
  resources :stocks

  resources :items do
    get 'search', on: :collection
  end

  resources :brands

  get '/test_ticket', to: 'ticket_test#ticket'
  #get '/report_order_item', to: 'report_order_item#index'
  get '/reports/items', to: 'reports#items'
  get '/reports/totals_day', to: 'reports#totals_day'


  #get 'search_brands', to: 'brands#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  belongs_to :item_type
  has_one :item_price, :dependent => :destroy
  has_one :stock, :dependent => :destroy

  validates_presence_of :name
  validates :name, uniqueness: true
  validates :code, uniqueness: true, allow_blank: true

  before_validation :default_values
  #before_destroy :drop_related

  protected
  def default_values
    
    if code.blank?
    	self.code = nil
    end
    
    if brand_id.nil?
      self.brand_id = Brand.find_by(name: "GENERICO").id
    end

    if item_type_id.nil?
      self.item_type_id = ItemType.find_by(name: "ITEM").id
    end

  end

#  def drop_related
#      Stock.where("item_id=?", id).delete_all
#      ItemPrice.where("item_id=?", id).delete_all
#    end

end

app/models/item_type.rb
class ItemType < ApplicationRecord
	has_many :item
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  ITEMS_PER_PAGE = 50

  # GET /items
  # GET /items.json
  def index
    @like_search = params.fetch(:like_search, "")
    @page = params.fetch(:page, 1).to_i

    words = @like_search.split(" ")
    sql = ""
    
    words.each_with_index do |word, index|
      if index > 0 
        sql += " and "
      end
      sql += "(lower(name) like lower('%#{word}%') or lower(description) like lower('%#{word}%') or lower(code) like lower('%#{word}%'))"
    end    

    @total_items = Item.where(sql).size
    @items = Item.where(sql).offset((@page-1)*ITEMS_PER_PAGE).limit(ITEMS_PER_PAGE).includes(:item_price, :brand, :stock)
    @total_pages = 0

    return if @total_items==0

    @mod_items = @total_items%ITEMS_PER_PAGE
    if @mod_items>0
      @total_pages = @total_items/ITEMS_PER_PAGE + 1
    else
      @total_pages = @total_items/ITEMS_PER_PAGE
    end
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new (item_params)

    if @item.save
      save_references_item
      redirect_to @item, notice: 'Articulo creado exitosamente'
    else
      render :new
    end
    
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      save_references_item
      redirect_to @item, notice: 'Articulo actualizado exitosamente'
    else
      render :edit
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if OrderItem.where(item_id: @item.id).size() >0 then
      redirect_to items_url, alert: 'Articulo en uso en una Orden pendiente, no se puede eliminar'
    else
      @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
    end
  end

  def search
    sql_where = "(item_prices.price > 0 or item_prices.variable_price)"
    words = params.fetch(:like_search, "").split(" ")
    code = params.fetch(:code, "")

    replacements = { "'" => "''"}

    words.each_with_index do |word, index|
      word = word.gsub(Regexp.union(replacements.keys), replacements)
      sql_where += " and (lower(items.name) like lower('%#{word}%') or lower(items.description) like lower('%#{word}%') or lower(code) like lower('%#{word}%') )"
    end

    if code.present? then
      code = code.gsub(Regexp.union(replacements.keys), replacements)
      sql_where += " and lower(items.code) = lower('#{code}')"
    end

    @items = Item.joins(:item_price).where(sql_where).includes(:item_price, :brand).limit(50)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:code, :brand_id, :name, :description)
    end

    def save_references_item

      if params[:item_price].present?
        variable_price = params[:item_price][:variable_price]
        price = params[:item_price][:price]
        price = price.to_f.round(2) if price.present?

        if @item.item_price.present?
          @item.item_price.price = price
          @item.item_price.variable_price = variable_price
          @item.item_price.save
        else
          ItemPrice.create! item_id: @item.id, price: price, variable_price: variable_price
        end

      end

      if params[:stock].present?
        units = params[:stock][:units]
        item_shareable = params[:stock][:item_shareable]
        buy_price = params[:stock][:buy_price]
        shared_stock = params[:stock][:shared_stock]
        shared_stock_item_id = params[:stock][:shared_stock_item_id]
        shared_stock_consume_units = params[:stock][:shared_stock_consume_units]

        units = units.to_f.round(2) if units.present?
        buy_price = buy_price.to_f.round(2) if buy_price.present?
        shared_stock_consume_units = shared_stock_consume_units.to_f.round(2) if shared_stock_consume_units.present?

        if @item.stock.present?
          @item.stock.units = units
          @item.stock.item_shareable = item_shareable
          @item.stock.buy_price = buy_price
          @item.stock.shared_stock = shared_stock
          @item.stock.shared_stock_item_id = shared_stock_item_id
          @item.stock.shared_stock_consume_units = shared_stock_consume_units
          @item.stock.save
        else
          Stock.create! item_id: @item.id, units: units, item_shareable: item_shareable, buy_price: buy_price, shared_stock: shared_stock, shared_stock_item_id: shared_stock_item_id, shared_stock_consume_units: shared_stock_consume_units
        end

      end

    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :code, 'Codigo', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :code, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :brand_id, 'Marca', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select(:brand_id, Brand.all.collect {|u| [u.name, u.id]}, {}, {:class => "form-control"}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :item_type_id, 'Tipo Articulo', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select(:item_type_id, ItemType.all.collect {|u| [u.name, u.id]}, {}, {:class => "form-control"}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :name, 'Nombre', :class => "col-sm-2 col-form-label font-weight-bold" %>
    <div class="col-sm-10">
      <%= form.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, 'Descripción', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :description, :class => "form-control" %>
    </div>
  </div>

  <h4>Precio a la Venta</h4>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold" for="item_price">Precio</label>
    <div class="col-sm-10">
      <% if @item.item_price.present? && (@item.item_price.price.blank? || @item.item_price.price<=0) %>
      <input class="form-control is-invalid" type="text" value="<%= @item.item_price.price if @item.item_price.present?%>" name="item_price[price]" id="item_price">
      <% else %>
      <input class="form-control" type="text" value="<%= @item.item_price.price if @item.item_price.present?%>" name="item_price[price]" id="item_price">
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="variable_price">Precio variable</label>
    <div class="col-sm-10">
      <input class="form-check-input" type="checkbox" value="1" name="item_price[variable_price]" id="variable_price" <%= 'checked' if @item.item_price.present? && @item.item_price.variable_price %>/>
    </div>
  </div>

  <h4>Existencias</h4>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="stock_units">Existencias</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" value="<%= @item.stock.units if @item.stock.present?%>" name="stock[units]" id="stock_units">
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="item_shareable">Articulo para compartir</label>
    <div class="col-sm-10">
      <input class="form-check-input" type="checkbox" value="1" name="stock[item_shareable]" id="item_shareable" <%= 'checked' if @item.stock.present? && @item.stock.item_shareable %>/>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="buy_price">Precio de Compra</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" value="<%= @item.stock.buy_price if @item.stock.present?%>" name="stock[buy_price]" id="buy_price">
    </div>
  </div>

  <h4>Existencias compartidas</h4>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="shared_stock">Existencia compartida</label>
    <div class="col-sm-10">
      <input class="form-check-input" type="checkbox" value="1" name="stock[shared_stock]" id="shared_stock" <%= 'checked' if @item.stock.present? && @item.stock.shared_stock %>/>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="shared_stock_item_id">Articulo para consumir</label>
    <div class="col-sm-10">
      <select class="form-control" name="stock[shared_stock_item_id]" id="shared_stock_item_id">
        <option></option>
        <% Item.joins(:stock).where('stocks.item_shareable = true').includes(:stock).order(:name).each do |item_shareable| %>
        <option <%= 'selected' if @item.stock.present? && @item.stock.shared_stock_item_id == item_shareable.id %> value="<%= item_shareable.id %>"><%= item_shareable.name %> existencias: <%= item_shareable.stock.units if item_shareable.stock.present? %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="shared_stock_consume_units">Consumo por este articulo</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" value="<%= @item.stock.shared_stock_consume_units if @item.stock.present?%>" name="stock[shared_stock_consume_units]" id="shared_stock_consume_units">
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/items/edit.html.erb
<h1>Editando Articulo</h1>

<%= render 'form', item: @item %>

<div class='float-right'>
<%= link_to 'Mostrar', @item %> |
<%= link_to 'Regresar', items_path %>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Articulos</h2>

<form action="/items" method="GET">
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" id="item-name" name="like_search" placeholder="Articulo" value="<%= @like_search %>"required />
      <div class="input-group-append">
        <button type="submit" class="btn btn-primary">Filtrar</button>
      </div>
    </div>
  </div>
</form>          

<nav aria-label="Page Navigation for items">
  <ul class="pagination justify-content-end">
    <li class="page-item <%= 'disabled' if @page-1<=0 %>">
      <%= link_to 'Anterior', items_path(page: @page-1, like_search: @like_search), class: "page-link" %>
    </li>
    <li class="page-item <%= 'disabled' if @page+1>@total_pages %>">
      <%= link_to 'Siguiente', items_path(page: @page+1, like_search: @like_search), class: "page-link" %>
    </li>
  </ul>
</nav>

<% if @items.size > 0 %>
Pagina <%= @page %> de <%= @total_pages %>, mostrando <%= @items.size %> articulos
<% else %>
No se encontrarón resultados
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead class="thead-dark">
      <tr>
        <th>Codigo</th>
        <th>Marca</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Precio Publico</th>
        <th>Existencias</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
            <tr>
              <td><%= item.code %></td>
              <td><%= item.brand.name %></td>
              <td><%= item.name %></td>
              <td><%= item.description %></td>
              <td><%= item.item_price.price if item.item_price.present? %></td>
              <td><%= item.stock.units if item.stock.present? %></td>
              <td><%= link_to 'Mostar', item %></td>
              <td><%= link_to 'Editar', edit_item_path(item) %></td>
              <td><%= link_to 'Eliminar', item, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
            </tr>
          <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Nuevo Articulo', new_item_path %>

app/views/items/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form', item: @item %>

<div class='float-right'>
<%= link_to 'Regresar', items_path %>
</div>

app/views/items/show.html.erb
<h2>Mostrando Articulo</h2>

<p id="notice"><%= notice %></p>

<div class="form-group row">
	<label for="code" class="col-sm-2 col-form-label">Codigo:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="code" value="<%= @item.code %>">
	</div>
</div>
<div class="form-group row">
	<label for="brand" class="col-sm-2 col-form-label">Marca:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="brand" value="<%= @item.brand.name %>">
	</div>
</div>
<div class="form-group row">
	<label for="item_type" class="col-sm-2 col-form-label">Tipo Articulo:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="item_type" value="<%= @item.item_type.name %>">
	</div>
</div>
<div class="form-group row">
	<label for="name" class="col-sm-2 col-form-label font-weight-bold">Nombre:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="name" value="<%= @item.name %>">
	</div>
</div>
<div class="form-group row">
	<label for="description" class="col-sm-2 col-form-label">Descripción:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="description" value="<%= @item.description %>">
	</div>
</div>

<h4>Precio a la Venta</h4>

<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold" for="item_price">Precio</label>
    <div class="col-sm-10">
      <% if @item.item_price.present? && (@item.item_price.price.blank? || @item.item_price.price<=0) %>
      <input class="form-control is-invalid" type="text" readonly value="<%= @item.item_price.price if @item.item_price.present?%>" id="item_price">
      <% else %>
      <input class="form-control" type="text" readonly value="<%= @item.item_price.price if @item.item_price.present?%>" id="item_price">
      <% end %>
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label" for="variable_price">Precio variable</label>
	<div class="col-sm-10">
	  <input class="form-check-input" type="checkbox" disabled value="1" name="item_price[variable_price]" id="variable_price" <%= 'checked' if @item.item_price.present? && @item.item_price.variable_price %>/>
	</div>
</div>

<h4>Existencias</h4>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="stock_units">Existencias</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" readonly value="<%= @item.stock.units if @item.stock.present?%>" id="stock_units">
    </div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label" for="item_shareable">Articulo para compartir</label>
	<div class="col-sm-10">
	  <input class="form-check-input" type="checkbox" disabled value="1" name="stock[item_shareable]" id="item_shareable" <%= 'checked' if @item.stock.present? && @item.stock.item_shareable %>/>
	</div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="buy_price">Precio de Compra</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" readonly value="<%= @item.stock.buy_price if @item.stock.present?%>" id="buy_price">
    </div>
</div>

<h4>Existencias compartidas</h4>

<div class="form-group row">
	<label class="col-sm-2 col-form-label" for="shared_stock">Existencia compartida</label>
	<div class="col-sm-10">
	  <input class="form-check-input" type="checkbox" disabled value="1" name="stock[shared_stock]" id="shared_stock" <%= 'checked' if @item.stock.present? && @item.stock.shared_stock %>/>
	</div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label" for="shared_stock_item_id">Articulo para consumir</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="shared_stock_item_id" value="<%= @item.stock.shared_stock_item_id %>">
	</div>
</div>

<div class="form-group row">
	<label class="col-sm-2 col-form-label" for="shared_stock_consume_units">Consumo por este articulo</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" value="<%= @item.stock.shared_stock_consume_units if @item.stock.present?%>" name="stock[shared_stock_consume_units]" id="shared_stock_consume_units">
	</div>
</div>

<div class='float-right'>
<%= link_to 'Editar', edit_item_path(@item) %> |
<%= link_to 'Regresar', items_path %>
</div>