config/routes.rb
Rails.application.routes.draw do

  resources :item_types
  devise_for :users
  root to: "orders#new"
  
  get '/orders/:id/submit', to: 'orders#submit'
  get '/orders/:id/resume', to: 'orders#resume'
  post '/orders/:id/complete', to: 'orders#complete'
  #get '/orders/:id/print_ticket', to: 'orders#print_ticket'
  get '/orders/print_info_pape', to: 'orders#print_info_pape'
  get '/orders/:id/print_order', to: 'orders#print_order'

  resources :order_item_histories
  resources :order_histories
  
  resources :orders do
    resources :order_items
  end
  
  resources :order_statuses
  resources :item_prices
  resources :stock_histories
  resources :stocks

  resources :items do
    get 'search', on: :collection
  end

  resources :brands

  get '/test_ticket', to: 'ticket_test#ticket'
  #get '/report_order_item', to: 'report_order_item#index'
  get '/reports/items', to: 'reports#items'
  get '/reports/totals_day', to: 'reports#totals_day'


  #get 'search_brands', to: 'brands#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  belongs_to :item_type
  has_one :item_price, :dependent => :destroy
  has_one :stock, :dependent => :destroy

  validates_presence_of :name
  validates :name, uniqueness: true
  validates :code, uniqueness: true, allow_blank: true

  before_validation :default_values
  #before_destroy :drop_related

  protected
  def default_values
    
    if code.blank?
    	self.code = nil
    end
    
    if brand_id.nil?
      self.brand_id = Brand.find_by(name: "GENERICO").id
    end

    if item_type_id.nil?
      self.item_type_id = ItemType.find_by(name: "ITEM").id
    end

  end

#  def drop_related
#      Stock.where("item_id=?", id).delete_all
#      ItemPrice.where("item_id=?", id).delete_all
#    end

end

app/models/item_price.rb
class ItemPrice < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if variable_price.blank?
    	self.variable_price = false
    end
    
  end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
	has_many :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_destroy :create_history

  private
  	def create_history
  	  order_history = OrderHistory.create!(order_id: id, name: name, order_status: order_status, count_items: count_items, subtotal_amount: subtotal_amount, total_discount: total_discount, total_amount: total_amount, paid: paid, change: change, discount_percentage: discount_percentage)

  	  order_items = OrderItem.where("order_id=?", id).includes(item: :item_price)

  	  order_items.each do |order_item|
        tmp_order_item_price = order_item.item.item_price
        tmp_price_per_unit = tmp_order_item_price.price

        if tmp_order_item_price.variable_price
          tmp_custom_price = order_item.custom_price
          tmp_price_per_unit = tmp_custom_price.to_f if tmp_custom_price.present?
        end

        OrderItemHistory.create! order_history_id: order_history.id, order_id: order_item.order_id, item_id: order_item.item_id, quantity: order_item.quantity, discount_amount_per_unit: order_item.discount_amount_per_unit, item_name: order_item.item.name, item_price: tmp_price_per_unit

        stockItem = order_item.item.stock
        if stockItem.blank?
          stockItem = Stock.create! item_id: order_item.item_id
        end

        if !stockItem.shared_stock
          stockItem.units = 0 if stockItem.units.blank?
          stockItem.units -= order_item.quantity
          stockItem.save
        else
          if stockItem.shared_stock_item_id.present?
            stockItemShared = Stock.find_by(item_id: stockItem.shared_stock_item_id)
            stockItemShared.units = 0 if stockItemShared.units.blank?
            stockItemShared.units -= (order_item.quantity*stockItem.shared_stock_consume_units)
            stockItemShared.save
          else
            puts "There is an error in configuration of shared item, please check"
            stockItem.units = 0 if stockItem.units.blank?
            stockItem.units -= order_item.quantity
            stockItem.save
          end
        end

      end
      OrderItem.where("order_id=?", id).delete_all

  	end
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :order_status
  has_many :order_item_histories

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order_item_history.rb
class OrderItemHistory < ApplicationRecord
  belongs_to :order_history
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item

  before_validation :default_values
 
  protected
  def default_values
    
    if item_shareable.blank?
    	self.item_shareable = false
    end
    
    if shared_stock.blank?
    	self.shared_stock = false
    end

  end
end

app/models/stock_history.rb
class StockHistory < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/item_prices_helper.rb
module ItemPricesHelper
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, 'Nombre', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :description, 'Descripción', :class => "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :description, :class => "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h2>Editando Marca</h2>

<%= render 'form', brand: @brand %>

<div class='float-right'>
<%= link_to 'Mostrar', @brand %> |
<%= link_to 'Regresar', brands_path %>
</div>

app/views/brands/index.html.erb
<h2>Marcas</h2>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead class="thead-dark">
      <tr>
        <th>Nombre</th>
        <th>Descripcón</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @brands.each do |brand| %>
        <tr>
          <td><%= brand.name %></td>
          <td><%= brand.description %></td>
          <td><%= link_to 'Mostrar', brand %></td>
          <td><%= link_to 'Editar', edit_brand_path(brand) %></td>
          <td><%= link_to 'Eliminar', brand, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Nueva Marca', new_brand_path %>

app/views/brands/new.html.erb
<h2>Nueva Marca</h2>

<%= render 'form', brand: @brand %>

<div class='float-right'>
<%= link_to 'Regresar', brands_path %>
</div>

app/views/brands/show.html.erb
<h2>Mostrando Marca</h2>

<p id="notice"><%= notice %></p>

<div class="form-group row">
	<label for="name" class="col-sm-2 col-form-label">Nombre:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="name" value="<%= @brand.name %>">
	</div>
</div>
<div class="form-group row">
	<label for="status" class="col-sm-2 col-form-label">Descripción:</label>
	<div class="col-sm-10">
	  <input type="text" readonly class="form-control" id="status" value="<%= @brand.description %>">
	</div>
</div>

<div class='float-right'>
<%= link_to 'Editar', edit_brand_path(@brand) %> |
<%= link_to 'Regresar', brands_path %>
</div>